server {
    listen 8080;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Это самое важное — обрабатывает запросы к корню
    location / {
        try_files $uri $uri/ /index.html;
    }
}
