server {
    listen 8080;
    server_name localhost;
    
    # Указываем корневую папку с файлами
    root /usr/share/nginx/html;
    
    # Главный файл — index.html
    index index.html;
    
    # Обработка запросов
    location / {
        try_files $uri $uri/ /index.html;
    }
}
